<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    <?php $product = json_decode($block->getAddToWishlistParams($block->getProduct()), true)['data']['product']; ?>
    <a href="#"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       onclick="addProductToWishlist()"
       data-action="add-to-wishlist"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif; ?>


<script>
    function addProductToWishlist() {
        require(['jquery','Magento_Customer/js/customer-data'], function($, customerData){
            var url = "<?php echo $block->getBaseUrl().'/wishlist/index/addtowishlist' ?>";
            $.ajax({
                url: url,
                method: "POST",
                data: { productId: <?php echo $product ?>},
                dataType: 'json',
                showLoader:true,
                cache: false,
                success: function(data){
                    var redirect = data.result.redirect;
                    if(redirect) {
                        window.location.href = '<?php echo $this->getUrl('customer/account/login') ?>';
                    } else {
                        var wishlist_link = '<a href="<?php echo $block->getBaseUrl().'/wishlist'?>">Click here for Wishlist</a>'
                        var msg = data.result.message;
                        var newmsg = msg+' '+wishlist_link;
                        customerData.set('messages', {
                            messages: [{
                                type: 'success',
                                text: newmsg
                            }]
                        });
                    }
                }
            });
        });
    }
</script>