<style>
    .header_account_link{
        color: white;
    }
    a{
        padding: 15px;
        margin-bottom: 10px;
    }
</style>
<div class="custom-link">
    <a class= "header_account_link" href="<?php echo $this->getUrl("contact-us");?>"><?php echo __('Contact Us')?></a>
    <a class= "header_account_link" href="<?php echo $this->getUrl("about-us");?>"><?php echo __('About Us')." " ?></a>
    <a class= "header_account_link" href="<?php echo $this->getUrl("customer-service");?>"><?php echo __('Customer Service')?></a>
</div>